name: Docker
on: workflow_dispatch

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Docker build
              run: echo "docker --build docker.io/${{vars.DOCKER_USERNAME}}/sas"

            - name: Docket Login
              run: echo "docker --login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}"

            - name: Docker publish
              run: echo "docker publish --image"

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        concurrency: 
            group: production-build # unique group name of job
            # cancel-in-progress: true # cancel other inprogress workflows and start new one in trigger again
            cancel-in-progress: false # it waits will thet previous workflow done its execution

        steps:
          - name: Docker run 
            timeout-minutes: 1 # workflow stops if it takes more time than defined timeout-minuts
            run: |
                echo "docker run 8080:8080 docker.io/contain_id/image_name:latest"
                sleep 6000s
