name: Strategy Matrix Configuration

on: workflow_dispatch

jobs:
    ################# In Below code we have to write repeated code for same job with different configuration. But Strategy matrix allows you to do this in same job.  ####################
    # deploy_on_ubuntu:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Echo docker details
    #           run: docker info

    #         - name: Run Image
    #           run: docker run hello-world

    # deploy_on_windows:
    #     runs-on: windows-latest
    #     steps:
    #         - name: Echo docker details
    #           run: docker info

    #         - name: Run Image
    #           run: docker run hello-world
    deploy:
        strategy:
            fail-fast: false
            max-parallel: 3 
            matrix:
              os: [ubuntu-latest, windows-latest, ubuntu-20.04]
              image: [hello-world, alpine]

              exclude:
                - image: alpine
                  os: windows-latest

              include:
                - image: amd64/alpine
                  os: ubuntu-20.04

        runs-on: ${{ matrix.os }}
        steps:
            - name: Echo docker details
              run: docker info

            - name: Run Image ${{ matrix.image }}
              run: docker run ${{ matrix.image }}