name: Generate ASCII ART

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
          - name: Install Cowsay
            run: sudo apt install cowsay -y
        
          - name: Execute Cowsay CMD 
            run: cowsay -f dragon "I love Linux!" >> dragon.txt


          - name: Upload Dragon.txt file
            uses: actions/upload-artifact@v4
            with:
              name: dragon-txt-file # Name of the artifact to upload.
              path: dragon.txt #  A file, directory or wildcard pattern that describes what to upload

    test_job_1:
        needs: build_job_1 # needs takes other job name value 
        runs-on: ubuntu-latest
        steps:
          - name: Download Dragon.txt file
            uses: actions/download-artifact@v5
            with:
                # Name of the artifact to download.
                # If unspecified, all artifacts for the run are downloaded.
                name: dragon-txt-file
                path: dragon.txt # Destination path ( Optional : Default is $GITHUB_WORKSPACE ). Supports basic tilde expansion.

          - name: list files
            run: ls
          - name: Test file exists
            run: grep -i "dragon" dragon.txt


    deploy_job_1:
        needs: [test_job_1] # this job depends on more than 1 jobs 
        runs-on: ubuntu-latest
        steps:
          - name: Download Dragon.txt file
            uses: actions/download-artifact@v5
            with:
                name: dragon-txt-file # Name of the artifact to download.

          - name: Display data
            run: cat dragon.txt

          - name: Deploy 
            run: echo 'Deploying....'